services:
  catalog.postgres:
    image: postgres:14-alpine
    container_name: catalog.postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

    ports:
      -  ${POSTGRES_PORT}:5432

    volumes:
      - postgres.catalog:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  catalog.pgadmin:
    image: dpage/pgadmin4
    container_name: catalog.pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"

    ports:
      - 8084:80

    depends_on:
      - catalog.postgres

volumes:
  postgres.catalog:
