# Create a new user
POST http://localhost:4200/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@local.local",
  "name": "Keks",
  "password": "123456"
}

###

# Login user by email and password
POST http://localhost:4200/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "login": "user@local.local",
  "password": "123456"
}

###

# Check user token
POST http://localhost:4200/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2FjMTIzOGVhNjk0MzBmMjk5OGYyZTUiLCJlbWFpbCI6InVzZXJAbG9jYWwubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczOTMzMDEyNSwiZXhwIjoxNzQwMTk0MTI1fQ._Db9xHUV7RozBHBZfWelcZhZf5QfjPeqQeDpjT1UwOs

###
