# Get products
GET http://localhost:4300/api/products HTTP/1.1

###

# Get products by filter, sort and page
GET http://localhost:4300/api/products?sortType=addedDate&sortDirection=desc&page=1 HTTP/1.1

###

# Get product by ID
GET http://localhost:4300/api/products/ed7a8bec-8582-472a-80c7-dd6d9d81427a HTTP/1.1
X-User-Id: 1111222233334444

###

# Create a new product
POST http://localhost:4300/api/products HTTP/1.1
X-User-Id: 1111222233334444
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

title title
--boundary
Content-Disposition: form-data; name="description"

description description
--boundary
Content-Disposition: form-data; name="imageFile"; filename="add-item-1.png"
Content-Type: image/png

< ../../../../../markup/img/content/add-item-1.png
--boundary
Content-Disposition: form-data; name="guitarType"

electro
--boundary
Content-Disposition: form-data; name="article"

article
--boundary
Content-Disposition: form-data; name="stringsCount"

4
--boundary
Content-Disposition: form-data; name="price"

10000
--boundary--

###

# Create a new product from api
POST http://localhost:3000/api/catalog/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzkzYjNlZWU4NTlmMWZjZjlmOThiYjYiLCJlbWFpbCI6InVzZXJAbG9jYWwubG9jYWwiLCJuYW1lIjoiTmFtZSIsImlhdCI6MTczNzk1MTAzOCwiZXhwIjoxNzQwNTQzMDM4fQ.uOyphexZXgzYL2lq678ErZGA2JSbDrSf-V67xpB2TeA
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

title title
--boundary
Content-Disposition: form-data; name="description"

description description
--boundary
Content-Disposition: form-data; name="imageFile"; filename="add-item-1.png"
Content-Type: image/png

< ../../../../../markup/img/content/add-item-1.png
--boundary
Content-Disposition: form-data; name="guitarType"

electro
--boundary
Content-Disposition: form-data; name="article"

article
--boundary
Content-Disposition: form-data; name="stringsCount"

4
--boundary
Content-Disposition: form-data; name="price"

10000
--boundary--

###

# Update product by ID
PUT http://localhost:4300/api/products/ff0c6fe5-d2bb-4cf3-a005-f117ab24b456 HTTP/1.1
X-User-Id: 1111222233334444
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

title title
--boundary
Content-Disposition: form-data; name="description"

description description
--boundary
Content-Disposition: form-data; name="imageFile"; filename="add-item-1.png"
Content-Type: image/png

< ../../../../../markup/img/content/add-item-1.png
--boundary
Content-Disposition: form-data; name="guitarType"

electro
--boundary
Content-Disposition: form-data; name="article"

article
--boundary
Content-Disposition: form-data; name="stringsCount"

6
--boundary
Content-Disposition: form-data; name="price"

11000
--boundary
Content-Disposition: form-data; name="addedDate"

15.03.2025
--boundary--

###

# Delete product by ID
DELETE http://localhost:4300/api/products/ff0c6fe5-d2bb-4cf3-a005-f117ab24b456 HTTP/1.1
X-User-Id: 1111222233334444

###
